// Runtime deployment config for THE CONTROL ROOM (Workshop 4).
// Plain script (not a module) so facilitators can swap values per event without
// touching application code.
//
// This is a separate instance from the Workshop 3 Skill Vault in ../escape-room/.
// The two games share an origin, so this copy uses its own localStorage keys
// ('controlRoom.*' — see js/state.js and js/leaderboard.js). Do not point both
// instances at the same keys or a W3 game in progress will bleed into W4.
window.SKILL_VAULT_CONFIG = {
  // Where the game fetches room content from (generated by tools/generate-hashes.mjs).
  roomsUrl: 'config/rooms.json',

  // Shared leaderboard backend (Supabase). Leave both empty to run in
  // local-only mode: codes still validate client-side, but the leaderboard and
  // facilitator view only see teams that played in the same browser.
  // The anon key is publishable by design — protect the table with RLS (see README).
  // Running LOCAL-ONLY for this cohort (both blank by design). Codes still
  // validate client-side and the game is fully playable; the leaderboard is
  // final-submission-only and per-device, and admin.html sees only teams that
  // played in this browser. The UI states this. To switch on a shared board,
  // create the table with the DDL in README.md and fill these three in.
  supabaseUrl: '',        // e.g. 'https://abcd1234.supabase.co'
  supabaseAnonKey: '',
  supabaseTable: 'control_room_teams',

  // Optional gate for admin.html: if set, the page requires ?key=<adminKey>.
  // A deterrent for curious participants, not real security.
  adminKey: ''
};
